import { z } from "zod";

const optionalText = z
  .string()
  .trim()
  .optional()
  .transform((v) => (v ? v : undefined));

export const invoiceFormSchema = z.object({
  // Auto-generated by the DB trigger — never user-entered, kept optional
  // here only so an edit form re-submitting the existing value doesn't fail.
  number: optionalText,
  title: z.string().trim().min(1, "Titre requis"),
  type: z.enum(["sent_to_partner", "received_from_supplier"]),
  document_type: z.enum(["quote", "purchase_order", "invoice", "credit_note"]).default("invoice"),
  supplier_name: optionalText,
  category_id: optionalText,
  amount: z.coerce.number().nonnegative(),
  tva: z.coerce.number().nonnegative().default(0),
  issue_date: z.string().trim().min(1, "Date requise"),
  due_date: optionalText,
  status: z.enum(["draft", "to_send", "sent", "pending", "paid", "partially_paid", "overdue", "cancelled"]),
  confidential_notes: optionalText,
});

export const invoicePaymentSchema = z.object({
  amount: z.coerce.number().positive("Le montant doit être supérieur à 0"),
  payment_date: z.string().trim().min(1, "Date requise"),
  payment_method: z.enum(["bank_transfer", "check", "cash", "card", "other"]).optional(),
  reference: optionalText,
  notes: optionalText,
});
